import { useMemo, useState } from 'react';
import type { ActionItem, GraphData } from '../../shared/types';
import { relativeDeadline } from '../lib/formatters';
import { StatusBadge } from './StatusBadge';

export function CommitmentGraph({ graph, actions, selectedId, onSelect }: { graph: GraphData; actions: ActionItem[]; selectedId?: string; onSelect: (id: string) => void }) {
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null);
  const nodes = useMemo(() => new Map(graph.nodes.map((node) => [node.id, node])), [graph.nodes]);
  const selected = actions.find((action) => action.id === selectedId);
  return <section className="graph-panel panel"><div className="section-heading graph-heading"><div><span className="eyebrow">The commitment graph</span><h2>See what unlocks what.</h2><p>Generated from the actions and dependencies KURIPPU found in this document.</p></div><div className="graph-controls"><button onClick={() => setZoom((value) => Math.min(1.6, value + 0.1))}>＋</button><span>{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((value) => Math.max(0.65, value - 0.1))}>−</button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }); }}>Reset</button></div></div><div className="graph-canvas" onMouseDown={(event) => setDragStart({ x: event.clientX - pan.x, y: event.clientY - pan.y })} onMouseMove={(event) => { if (dragStart) setPan({ x: event.clientX - dragStart.x, y: event.clientY - dragStart.y }); }} onMouseUp={() => setDragStart(null)} onMouseLeave={() => setDragStart(null)}><svg viewBox="0 0 900 460" role="img" aria-label="Interactive commitment dependency graph"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#b9b7b1" /></marker></defs><g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}>{graph.edges.map((edge) => { const from = nodes.get(edge.from); const to = nodes.get(edge.to); if (!from || !to) return null; const hot = selectedId === edge.from || selectedId === edge.to; return <line key={edge.id} x1={from.x + 82} y1={from.y + 34} x2={to.x - 8} y2={to.y + 34} className={hot ? 'graph-edge is-hot' : 'graph-edge'} markerEnd="url(#arrow)" />; })}{graph.nodes.map((node) => <g key={node.id} className={`graph-node graph-node--${node.status} ${selectedId === node.id ? 'is-selected' : ''}`} onClick={() => onSelect(node.id)}><rect x={node.x} y={node.y} rx="12" width="165" height="68" /><circle cx={node.x + 18} cy={node.y + 20} r="5" /><text x={node.x + 32} y={node.y + 24}>{node.shortLabel}</text><text x={node.x + 18} y={node.y + 49} className="graph-node__meta">{node.status.replace('_', ' ')}{node.deadline ? ` · ${relativeDeadline(actions.find((action) => action.id === node.id)!)}` : ''}</text></g>)}</g></svg></div>{selected && <div className="graph-detail"><div><span className="eyebrow">Selected action</span><strong>{selected.title}</strong><span>{selected.description}</span></div><StatusBadge status={selected.status} /><button className="text-button" onClick={() => onSelect(selected.id)}>Open details ↗</button></div>}</section>;
}
