import { db } from './client';
import type { ActionItem, DocumentRecord } from '../../shared/types';
import { refreshDerivedStatuses } from '../services/dependencyEngine';

const iso = (date: string) => new Date(`${date}T18:00:00.000Z`).toISOString();

function action(documentId: string, id: string, title: string, description: string, deadline: string | null, priority: ActionItem['priority'], dependsOn: string[], requiredDocuments: string[], consequence: string, sourceText: string, sourcePage: number, status: ActionItem['status'] = 'pending'): ActionItem {
  return { id, documentId, title, description, deadline, deadlineLabel: deadline ? new Date(deadline).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'No deadline found', deadlineUncertain: false, priority, status, dependsOn, requiredDocuments, consequence, sourceText, sourcePage, confidence: 0.94, notes: '', createdAt: iso('2026-10-01'), updatedAt: iso('2026-10-01') };
}

function seedDocument(document: DocumentRecord): void {
  refreshDerivedStatuses(document);
  db.saveDocument(document);
}

export function seedDemoData(): void {
  if (db.listDocuments().length) return;
  const internshipId = 'doc-internship';
  const internshipActions = [
    action(internshipId, 'act-review-offer', 'Review offer details', 'Read the role, stipend, joining date, and acceptance terms before replying.', iso('2026-10-06'), 'critical', [], [], 'You may accept terms without noticing a condition.', 'Please review the offer details and confirm your acceptance by 6 October 2026.', 1, 'completed'),
    action(internshipId, 'act-id-proof', 'Upload ID proof', 'Prepare and upload a clear government ID proof.', iso('2026-10-07'), 'high', ['act-review-offer'], ['Government ID proof'], 'The application cannot be completed without identity verification.', 'Upload a scanned copy of your government ID proof along with the acceptance form.', 2),
    action(internshipId, 'act-sign-offer', 'Sign offer letter', 'Sign the final offer letter after confirming the details.', iso('2026-10-08'), 'high', ['act-review-offer'], [], 'The internship offer may remain unconfirmed.', 'Sign and return the offer letter by 8 October 2026.', 2),
    action(internshipId, 'act-send-acceptance', 'Send acceptance email', 'Email the signed letter and ID proof to the coordinator.', iso('2026-10-09'), 'critical', ['act-id-proof', 'act-sign-offer'], ['Signed offer letter', 'Government ID proof'], 'Your place cannot be reserved until both files are received.', 'Send the signed offer letter and ID proof to internships@northstar.example by 9 October 2026.', 3),
  ];
  seedDocument({ id: internshipId, name: 'Internship Offer Letter.pdf', safeFilename: 'internship-offer-letter.pdf', type: 'offer letter', mimeType: 'application/pdf', size: 482000, uploadDate: iso('2026-10-01'), status: 'ready', sourceType: 'demo', title: 'Northstar internship offer', documentType: 'offer_letter', summary: 'A summer product internship offer with a short acceptance window. The commitment chain ends when the signed offer and identity proof reach the coordinator.', confidence: 0.94, issueDate: iso('2026-10-01'), pageCount: 3, pages: [{ page: 1, text: 'Northstar Labs Internship Offer Letter. Please review the offer details and confirm your acceptance by 6 October 2026.' }, { page: 2, text: 'Upload a scanned copy of your government ID proof along with the acceptance form. Sign and return the offer letter by 8 October 2026.' }, { page: 3, text: 'Send the signed offer letter and ID proof to internships@northstar.example by 9 October 2026.' }], importantDates: [{ label: 'Acceptance deadline', raw: '6 October 2026', normalized: '2026-10-06', uncertain: false, sourcePage: 1 }, { label: 'Return signed offer', raw: '8 October 2026', normalized: '2026-10-08', uncertain: false, sourcePage: 2 }, { label: 'Send documents', raw: '9 October 2026', normalized: '2026-10-09', uncertain: false, sourcePage: 3 }], requirements: ['Government ID proof', 'Signed offer letter', 'Acceptance email'], responsibleParties: ['Internship candidate', 'Northstar Labs coordinator'], consequences: ['The place cannot be reserved until the signed offer and ID proof are received.'], actions: internshipActions, rawText: internshipActions.map((item) => item.sourceText).join('\n'), analysisMode: 'demo' });

  const scholarshipId = 'doc-scholarship';
  const scholarshipActions = [
    action(scholarshipId, 'act-scholarship-profile', 'Complete scholarship profile', 'Fill the online profile with academic and family details.', iso('2026-10-12'), 'high', [], [], 'The application will remain in draft.', 'Complete the scholarship profile with academic and family details before 12 October 2026.', 1),
    action(scholarshipId, 'act-scholarship-income', 'Attach income certificate', 'Upload a current income certificate issued by the proper authority.', iso('2026-10-14'), 'high', ['act-scholarship-profile'], ['Income certificate'], 'The review committee may mark the submission incomplete.', 'Attach an income certificate issued within the last financial year.', 2),
    action(scholarshipId, 'act-scholarship-submit', 'Submit scholarship application', 'Review all fields and submit the final application.', iso('2026-10-15'), 'critical', ['act-scholarship-profile', 'act-scholarship-income'], ['Income certificate', 'Mark sheets'], 'Late applications will not be considered for this cycle.', 'The final application must be submitted online by 15 October 2026.', 3),
  ];
  seedDocument({ id: scholarshipId, name: 'Merit scholarship notice.pdf', safeFilename: 'merit-scholarship-notice.pdf', type: 'scholarship notice', mimeType: 'application/pdf', size: 392000, uploadDate: iso('2026-09-28'), status: 'ready', sourceType: 'demo', title: 'Merit scholarship notice', documentType: 'scholarship_notice', summary: 'A scholarship notice with a three-step application chain: profile, income proof, then final submission.', confidence: 0.91, issueDate: iso('2026-09-25'), pageCount: 3, pages: [{ page: 1, text: 'Complete the scholarship profile with academic and family details before 12 October 2026.' }, { page: 2, text: 'Attach an income certificate issued within the last financial year.' }, { page: 3, text: 'The final application must be submitted online by 15 October 2026.' }], importantDates: [{ label: 'Profile deadline', raw: '12 October 2026', normalized: '2026-10-12', uncertain: false, sourcePage: 1 }, { label: 'Submission deadline', raw: '15 October 2026', normalized: '2026-10-15', uncertain: false, sourcePage: 3 }], requirements: ['Income certificate', 'Mark sheets'], responsibleParties: ['Student applicant', 'Scholarship committee'], consequences: ['Late applications will not be considered for this cycle.'], actions: scholarshipActions, rawText: scholarshipActions.map((item) => item.sourceText).join('\n'), analysisMode: 'demo' });

  const eventId = 'doc-event';
  const eventActions = [
    action(eventId, 'act-event-form', 'Complete registration form', 'Enter participant details and select your track.', iso('2026-10-20'), 'medium', [], [], 'Your registration will remain incomplete.', 'Complete the registration form and select one track by 20 October 2026.', 1, 'completed'),
    action(eventId, 'act-event-payment', 'Confirm attendance', 'Use the confirmation link to reserve your seat.', iso('2026-10-22'), 'low', ['act-event-form'], [], 'Your seat may be released to the waitlist.', 'Confirm attendance through the link in the registration email by 22 October 2026.', 2, 'completed'),
  ];
  seedDocument({ id: eventId, name: 'Design systems meetup notice.pdf', safeFilename: 'design-systems-meetup-notice.pdf', type: 'event notice', mimeType: 'application/pdf', size: 250000, uploadDate: iso('2026-09-20'), status: 'ready', sourceType: 'demo', title: 'Design systems meetup notice', documentType: 'event_notice', summary: 'A completed two-step registration flow for the October design systems meetup.', confidence: 0.89, issueDate: iso('2026-09-18'), pageCount: 2, pages: [{ page: 1, text: 'Complete the registration form and select one track by 20 October 2026.' }, { page: 2, text: 'Confirm attendance through the link in the registration email by 22 October 2026.' }], importantDates: [{ label: 'Registration', raw: '20 October 2026', normalized: '2026-10-20', uncertain: false, sourcePage: 1 }], requirements: ['Registration form'], responsibleParties: ['Participant'], consequences: ['Your seat may be released to the waitlist.'], actions: eventActions, rawText: eventActions.map((item) => item.sourceText).join('\n'), analysisMode: 'demo' });
}
