import { useState } from 'react';
import { BrandMark } from '../components/BrandMark';

export function LandingPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="landing-page"><header className="landing-nav"><BrandMark /><nav className={menuOpen ? 'landing-links is-open' : 'landing-links'}><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a><a href="#roadmap" onClick={() => setMenuOpen(false)}>Roadmap</a></nav><div className="landing-actions"><button className="nav-login" onClick={() => onNavigate('/app')}>Open workspace</button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? '×' : '☰'}</button></div></header><main>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">Document-to-action intelligence <span className="eyebrow-dot" /></span><h1>Turn documents<br /><em>into actions.</em></h1><p className="hero-lede">AI that finds what your documents expect you to do — deadlines, tasks, dependencies, and consequences.</p><div className="hero-cta"><button className="primary-button" onClick={() => onNavigate('/upload')}>Analyze a document <span>↗</span></button><a className="secondary-link" href="#how-it-works">See how it works <span>↓</span></a></div><div className="hero-proof"><span className="proof-avatars"><i>AR</i><i>VP</i><i>NK</i></span><span>Built for the things you<br /><strong>cannot afford to forget.</strong></span></div></div><div className="hero-visual"><div className="hero-paper"><div className="paper-top"><span className="paper-logo">NORTHSTAR <small>LABS</small></span><span className="paper-tag">OFFER LETTER</span></div><div className="paper-title">Your internship<br />starts here.</div><div className="paper-lines"><i /><i /><i /><i /><i /></div><div className="paper-callout"><span>↳</span><div><strong>Accept by 06 Oct 2026</strong><small>Page 1 · 96% confidence</small></div></div><div className="paper-footer"><span>Northstar Labs</span><span>01 / 03</span></div></div><div className="hero-action-card"><div className="mini-card-head"><span className="mini-signal" /> <span>YOUR NEXT STEP</span><span className="mini-arrow">↗</span></div><strong>Upload ID proof</strong><span className="mini-due">Due tomorrow · Critical</span><div className="mini-progress"><i /></div><span className="mini-foot">Unlocks 1 dependent action</span></div><div className="hero-caption"><span className="caption-line" /> <span>From 30 pages of text to a plan you can trust.</span></div></div></section>
    <section className="marquee-strip"><div>DOCUMENT <span>↓</span> INFORMATION <span>↓</span> COMMITMENTS <span>↓</span> ACTIONS <span>↓</span> DEADLINES <span>↓</span> DEPENDENCIES <span>↓</span> PRIORITY <span>↓</span> ACTION PLAN</div></section>
    <section className="story-section" id="how-it-works"><div className="story-intro"><span className="eyebrow">The missing layer</span><h2>Most tools tell you<br />what it <em>says.</em></h2><p>KURIPPU tells you what it requires you to do next. Because important information is only useful when it moves you forward.</p></div><div className="steps"><div className="step-card"><span className="step-number">01</span><div className="step-icon">↑</div><h3>Upload</h3><p>Drop in an offer letter, circular, notice, or form. KURIPPU reads the fine print.</p></div><div className="step-card step-card--active"><span className="step-number">02</span><div className="step-icon">✦</div><h3>Understand</h3><p>Commitments, dates, requirements and consequences become a structured action plan.</p></div><div className="step-card"><span className="step-number">03</span><div className="step-icon">↗</div><h3>Act</h3><p>Follow the path. See dependencies unlock. Know what to do before a deadline finds you.</p></div></div></section>
    <section className="graph-story"><div className="graph-story-copy"><span className="eyebrow">The signature feature</span><h2>Every commitment<br />has a <em>shape.</em></h2><p>The commitment graph connects actions, prerequisites, deadlines and consequences. So one completed task can change what is possible next.</p><button className="outline-button" onClick={() => onNavigate('/app')}>Explore the workspace ↗</button></div><div className="story-graph"><div className="story-node story-node--doc"><span>DOCUMENT</span><strong>Internship offer</strong></div><div className="story-line story-line--one" /><div className="story-node story-node--review"><span>01 · READY</span><strong>Review terms</strong></div><div className="story-branch"><div className="story-line story-line--branch" /><div className="story-node story-node--left"><span>02 · PENDING</span><strong>Upload ID proof</strong></div><div className="story-node story-node--right"><span>02 · PENDING</span><strong>Sign offer</strong></div></div><div className="story-line story-line--merge" /><div className="story-node story-node--final"><span>03 · BLOCKED</span><strong>Send acceptance</strong></div></div></section>
    <section className="pricing-section" id="pricing"><div className="pricing-intro"><span className="eyebrow">Simple by design</span><h2>Start with clarity.<br /><em>Keep your momentum.</em></h2></div><div className="pricing-cards"><article><span className="plan-name">FREE</span><strong>₹0</strong><p>For the commitments on your desk right now.</p><ul><li>5 documents / month</li><li>Action plans + deadlines</li><li>Source-grounded answers</li></ul><button className="outline-button" onClick={() => onNavigate('/upload')}>Start for free ↗</button></article><article className="pricing-card--featured"><span className="plan-name">PRO <b>Most useful</b></span><strong>₹99<small>/month</small></strong><p>For people building a system they can trust.</p><ul><li>Unlimited documents</li><li>Advanced deadline tracking</li><li>Smart reminders + calendar</li></ul><button className="primary-button" onClick={() => onNavigate('/upload')}>Choose Pro ↗</button></article><article><span className="plan-name">BUSINESS</span><strong>₹499<small>/user/month</small></strong><p>For teams that share the work behind the work.</p><ul><li>Shared action plans</li><li>Team document intelligence</li><li>Admin dashboard</li></ul><button className="outline-button" onClick={() => onNavigate('/app')}>See the workspace ↗</button></article></div></section>
    <section className="roadmap-section" id="roadmap"><div><span className="eyebrow">What comes next</span><h2>A better way to<br /><em>keep your word.</em></h2></div><div className="roadmap"><div className="roadmap-item is-current"><span>01</span><div><strong>Document intelligence</strong><small>Now · The action layer</small></div></div><div className="roadmap-item"><span>02</span><div><strong>Email + calendar</strong><small>Next · Reminders that know context</small></div></div><div className="roadmap-item"><span>03</span><div><strong>WhatsApp + mobile</strong><small>Later · Commitments wherever you are</small></div></div><div className="roadmap-item"><span>04</span><div><strong>Enterprise automation</strong><small>Future · Workflows that move themselves</small></div></div></div></section>
  </main><footer className="landing-footer"><BrandMark /><span>© 2026 KURIPPU. The action layer for documents people cannot afford to forget.</span><button onClick={() => onNavigate('/app')}>Open workspace ↗</button></footer></div>;
}
