import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { formatDate, relativeDeadline, typeLabel } from '../lib/formatters';
import type { DocumentRecord } from '../../shared/types';

export function LibraryPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [documents, setDocuments] = useState<Array<DocumentRecord & { completion: number }>>([]);
  const [query, setQuery] = useState(() => new URLSearchParams(window.location.search).get('search') ?? '');
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.documents().then((result) => setDocuments(result.documents)).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); if (!q) return documents; return documents.filter((document) => JSON.stringify(document).toLowerCase().includes(q)); }, [documents, query]);
  return <div className="page library-page"><div className="page-heading"><div><span className="eyebrow">Your source of truth</span><h1>My documents<span className="heading-dot">.</span></h1><p>Every document becomes a living plan, not another file to forget.</p></div><button className="primary-button" onClick={() => onNavigate('/upload')}>＋ Analyze document</button></div><div className="library-toolbar"><div className="library-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search documents, actions, deadlines…" /></div><div className="library-filter"><span>{filtered.length} documents</span><button className="filter-button">All types⌄</button></div></div>{loading ? <div className="loading-state"><div className="loading-bar" /><p>Indexing your documents…</p></div> : <div className="document-grid">{filtered.map((document) => { const upcoming = document.actions.filter((action) => action.deadline && action.status !== 'completed').sort((a, b) => new Date(a.deadline!).getTime() - new Date(b.deadline!).getTime())[0]; return <button className="document-card" key={document.id} onClick={() => onNavigate(`/documents/${document.id}`)}><div className="document-card__top"><div className={`doc-icon doc-icon--${document.sourceType}`}>{document.sourceType === 'demo' ? '✦' : '▤'}</div><span className="document-source">{document.sourceType === 'demo' ? 'Demo document' : 'Uploaded'}</span><span className="card-arrow">↗</span></div><h3>{document.title}</h3><p>{document.summary}</p><div className="document-card__meta"><span>{typeLabel(document.type)}</span><span>Added {formatDate(document.uploadDate)}</span></div><div className="document-card__bottom"><div><strong>{document.actions.filter((action) => action.status !== 'completed').length}</strong><span>actions left</span></div><div><strong>{document.completion}%</strong><span>complete</span></div>{upcoming && <div className="deadline-mini"><span>Next deadline</span><strong>{relativeDeadline(upcoming)}</strong></div>}</div><div className="document-progress"><i style={{ width: `${document.completion}%` }} /></div></button>})}{!filtered.length && <div className="empty-state panel"><span>⌕</span><h3>No documents match that search.</h3><p>Try a deadline, action, or source phrase.</p></div>}</div>}</div>;
}
